### ISSUE TITLE
Activerecord 4 compatibility?

### ISSUE THREAD

**Issue by matrushka** [fiksu/partitioned#44]
Is partitioned compatible with AR4? I couldn't find anything about it in docs or anywhere else.

**Comment by dkhofer** [comment]
After a ridiculously long delay, I've merged changes to support 4.0 and 4.1 to master.

4.0 is available both here and at rubygems.org with a version of 2.0.0
4.1 is available at head here.

1.3.5 is the last version supporting rails 3, 2.0 and higher are breaking changes.

There were new AR monkeypatches involved.  The less said the better.

It is unlikely that Fiksu will be actively maintaining this gem going forward.  I'm planning to tag master with a 2.1.0 tag (for rails 4.1) tomorrow and push that to rubygems.  I'm also planning to work on a branch to support 4.2 but I haven't started it yet.  I do not foresee Fiksu upgrading this gem for rails 5.0, so someone will likely have to fork this repo and do the upgrade work themselves.

I'm closing this out.  If someone wants rails 4.2 support, please open a separate issue.
