### ISSUE TITLE
Unable to create partition. 

### ISSUE THREAD

**Issue by sushantt2099** [fiksu/partitioned#55]
I am unable to create partition. I am getting NoMethodError exception .rvm/gems/ruby-2.0.0-p247/gems/partitioned-1.3.4/lib/monkey_patch_postgres.rb:21:in `check_constraint': undefined method `<<' for nil:NilClass (NoMethodError), when calling `create_new_partition_tables` method. I also tried running script from the example.

Here is the full trace:
	from /Users/sushant/.rvm/gems/ruby-2.0.0-p247/gems/partitioned-1.3.4/lib/partitioned/partitioned_base/sql_adapter.rb:166:in `block in create_partition_table'
	from /Users/sushant/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.1.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:198:in `create_table'
	from /Users/sushant/.rvm/gems/ruby-2.0.0-p247/gems/partitioned-1.3.4/lib/partitioned/partitioned_base/sql_adapter.rb:161:in `create_partition_table'
	from /Users/sushant/.rvm/gems/ruby-2.0.0-p247/gems/partitioned-1.3.4/lib/partitioned/partitioned_base/partition_manager.rb:135:in `create_new_partition'
	from /Users/sushant/.rvm/gems/ruby-2.0.0-p247/gems/partitioned-1.3.4/lib/partitioned/partitioned_base/partition_manager.rb:57:in `block in create_new_partition_tables'
	from /Users/sushant/.rvm/gems/ruby-2.0.0-p247/gems/partitioned-1.3.4/lib/partitioned/partitioned_base/partition_manager.rb:56:in `each'
	from /Users/sushant/.rvm/gems/ruby-2.0.0-p247/gems/partitioned-1.3.4/lib/partitioned/partitioned_base/partition_manager.rb:56:in `create_new_partition_tables'
	from /Users/sushant/.rvm/gems/ruby-2.0.0-p247/gems/partitioned-1.3.4/lib/partitioned/partitioned_base.rb:419:in `create_new_partition_tables'
	from company_id.rb:344:in `<top (required)>'
	from /Users/sushant/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.1.1/lib/rails/commands/runner.rb:60:in `load'
	from /Users/sushant/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.1.1/lib/rails/commands/runner.rb:60:in `<top (required)>'
	from /Users/sushant/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.1.1/lib/rails/commands/commands_tasks.rb:128:in `require'
	from /Users/sushant/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.1.1/lib/rails/commands/commands_tasks.rb:128:in `require_command!'
	from /Users/sushant/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.1.1/lib/rails/commands/commands_tasks.rb:95:in `runner'
	from /Users/sushant/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.1.1/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	from /Users/sushant/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.1.1/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'

**Comment by dkhofer** [comment]
Rails 4.1 is supported now, closing this out.
