### ISSUE TITLE
docs issue

### ISSUE THREAD

**Issue by jaypatrickhoward** [fiksu/partitioned#56]
To enable a model for bulk inserting the docs recommend doing this:

```
class Company < ActiveRecord::Base
  extend Partitioned::BulkMethodsMixin
end
```

This doesn't actually work, though, since BulkMethodsMixin was moved to its own gem (which is required by 'partitioned').  Instead I had to:

```
class Company < ActiveRecord::Base
  extend BulkMethodsMixin
end
```

**Comment by dkhofer** [comment]
I assume you meant here? https://github.com/fiksu/partitioned/wiki/Bulk-Methods

If so, that's fixed.  Thanks for letting us know about the bad line.
